# Generated by Django 3.1.5 on 2021-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='participacoes',
        ),
        migrations.AddField(
            model_name='musica',
            name='participacoes',
            field=models.ManyToManyField(related_name='participacoes', to='membro.Membro'),
        ),
    ]
