# Generated by Django 3.1.5 on 2021-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
        ('musica', '0002_auto_20210126_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='participacoes',
            field=models.ManyToManyField(blank=True, null=True, related_name='participacoes', to='membro.Membro'),
        ),
    ]
