# Generated by Django 3.1.5 on 2021-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0001_initial'),
        ('musica', '0003_auto_20210127_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='participacoes',
            field=models.ManyToManyField(blank=True, related_name='participacoes', to='membro.Membro'),
        ),
    ]
