# Generated by Django 3.1.5 on 2021-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data fundação')),
                ('membros', models.ManyToManyField(related_name='bandas', to='membro.Membro')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
            },
        ),
    ]
