# Generated by Django 3.1.5 on 2021-01-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banda', '0001_initial'),
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banda.banda')),
                ('musicas', models.ManyToManyField(related_name='musicas', to='musica.Musica')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
    ]
