# Generated by Django 3.1.5 on 2021-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
